### ISSUE TITLE
Clarification when configurating a local LLM for demos/space_colony/simulation.py?

### ISSUE THREAD

**Issue by jim-plus** [fablestudio/fable-saga#30]
I would appreciate some clarity on how many LLM instances the demo uses. Is it one per agent? If it's more than one instance, it would seem the better approach is to use an API to access a local LLM that is up and running rather modifying fable_saga/__init__.py to create an instance of LlamaCpp(). (I ran into an out of memory error when a second LlamaCpp() instance was attempted.)

**Comment by frankcarey** [comment]
Previously we were storing more data with the fable_saga.Agent and it needed to have it's own id to reference memories, etc. That was on it's way out where we let people just define `skills` and then everything else goes into `context` so that there really isn't any state left in `fable_saga.Agent`. I just removed the last `id` requirement from it in this latest PR, which should get merged tomorrow.

https://github.com/fablestudio/fable-saga/pull/31

So, if you are loading your model into memory, you should only have to do it once now, but it brings up that you shouldn
t have to modify anything in `/fable_saga` folder in order to extend it to something custom.. instead,  you probably want to create a custom langchain model and pass that in... actually it looks like they already have support for that in langchain..

https://python.langchain.com/docs/integrations/llms/llamacpp

**Comment by frankcarey** [comment]
Ok, that's now merged and a new release v0.3.0 is available.
